### PR TITLE
Create React App with default settings

### LINKED ISSUE #2: [1pt] Setup
1. Repository Created.
2. Set Dev Branch.
3. Add Liners.
4. Update Readme.md
5. Add MIT License File.

### PR DESCRIPTION
**Pull request by cancelei**
Hello,

I ran Create React App with default settings and made adjustments at the License.md.

Let me know what you think.

### CODE REVIEW

**Comment by MasumaJaffery** [comment]
Hello @cancelei, You did a great Job 👍🏻

**Comment by najibullahjafari** [comment]
@MasumaJaffery Did you added eslint and stylelint in dev?

**Comment by MasumaJaffery** [comment]
Yes

**Review by najibullahjafari — APPROVED** [review]
You did a great job!

**Pull request merged**
